services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx_conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  sublimeful:
    container_name: sublimeful
    build: sublimeful
    restart: unless-stopped
