services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx_conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  sublimeful:
    container_name: Sublimeful
    build: Sublimeful
    restart: unless-stopped
  interviewai-redis:
    image: redis:latest
    container_name: InterviewAI-redis
  interviewai:
    container_name: InterviewAI
    build: InterviewAI
    depends_on:
      - interviewai-redis
